export const events = [
  {
    slug: "react-conf-india-2024",
    image: "/images/event1.png",
    title: "React Conf India 2024",
    location: "Bengaluru, KA",
    date: "March 15, 2024",
    time: "9:00 AM - 6:00 PM (IST)",
  },
  {
    slug: "nextjs-summit-india",
    image: "/images/event2.png",
    title: "Next.js Summit India",
    location: "Hyderabad, TS",
    date: "April 22, 2024",
    time: "10:00 AM - 5:00 PM (IST)",
  },
  {
    slug: "javascript-world-india",
    image: "/images/event3.png",
    title: "JavaScript India Conference",
    location: "Mumbai, MH",
    date: "May 8, 2024",
    time: "9:30 AM - 7:00 PM (IST)",
  },
  {
    slug: "ai-hackathon-india-2024",
    image: "/images/event4.png",
    title: "AI Innovation Hackathon India",
    location: "Pune, MH",
    date: "June 14-16, 2024",
    time: "48 Hours (IST)",
  },
  {
    slug: "web3-developer-meetup-mumbai",
    image: "/images/event5.png",
    title: "Web3 Developer Meetup — Mumbai",
    location: "Mumbai, MH",
    date: "July 20, 2024",
    time: "6:00 PM - 9:00 PM (IST)",
  },
  {
    slug: "fullstack-conference-india",
    image: "/images/event6.png",
    title: "Full Stack Conference India",
    location: "Chennai, TN",
    date: "August 12, 2024",
    time: "9:00 AM - 6:00 PM (IST)",
  },
  {
    slug: "devops-unleashed-india",
    image: "/images/event1.png",
    title: "DevOps Unleashed India",
    location: "New Delhi, DL",
    date: "September 5, 2024",
    time: "8:00 AM - 5:30 PM (IST)",
  },
  {
    slug: "mobile-dev-summit-india",
    image: "/images/event2.png",
    title: "Mobile Development Summit India",
    location: "Bengaluru, KA",
    date: "October 18, 2024",
    time: "9:30 AM - 6:00 PM (IST)",
  },
  {
    slug: "cybersecurity-conference-india",
    image: "/images/event3.png",
    title: "Cybersecurity India Conference",
    location: "Kolkata, WB",
    date: "November 2, 2024",
    time: "9:00 AM - 7:00 PM (IST)",
  },
  {
    slug: "data-science-hackathon-india",
    image: "/images/event4.png",
    title: "Data Science Hackathon India",
    location: "Bengaluru, KA",
    date: "December 7-9, 2024",
    time: "72 Hours (IST)",
  },
  {
    slug: "cloud-native-meetup-india",
    image: "/images/event5.png",
    title: "Cloud Native Meetup — Pune",
    location: "Pune, MH",
    date: "January 15, 2025",
    time: "6:30 PM - 9:00 PM (IST)",
  },
  {
    slug: "frontend-masters-india",
    image: "/images/event6.png",
    title: "Frontend Masters Conference India",
    location: "Jaipur, RJ",
    date: "February 28, 2025",
    time: "9:00 AM - 5:00 PM (IST)",
  },
];
